language: r
cache: packages

r:
  - oldrel
  - release
  - devel

notifications:
  email:
    recipients:
     - janani@msu.edu
     # - alerts+jananiravi21@gmail.com
    on_success: change
    on_failure: change

branches:
  #except:
  #- legacy
  #- experimental
  only:
  - master